// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5BA0OxSlI-4PzPkAlLU-0_NIAEFgFPiM',
    appId: '1:834509746782:web:cd4935a16951db5783facf',
    messagingSenderId: '834509746782',
    projectId: 'storytelling-audio-web-bc2eb',
    authDomain: 'storytelling-audio-web-bc2eb.firebaseapp.com',
    storageBucket: 'storytelling-audio-web-bc2eb.firebasestorage.app',
    measurementId: 'G-7EFYM09EMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5aXqTfFFJCOU4pm3vfxexMC3r3mAPbQ0',
    appId: '1:834509746782:android:5cb5c10699d9798a83facf',
    messagingSenderId: '834509746782',
    projectId: 'storytelling-audio-web-bc2eb',
    storageBucket: 'storytelling-audio-web-bc2eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3vQeRLPTDcLDZzx-mEeD9FiqlzelHOF0',
    appId: '1:834509746782:ios:8610a70417261fb783facf',
    messagingSenderId: '834509746782',
    projectId: 'storytelling-audio-web-bc2eb',
    storageBucket: 'storytelling-audio-web-bc2eb.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3vQeRLPTDcLDZzx-mEeD9FiqlzelHOF0',
    appId: '1:834509746782:ios:8610a70417261fb783facf',
    messagingSenderId: '834509746782',
    projectId: 'storytelling-audio-web-bc2eb',
    storageBucket: 'storytelling-audio-web-bc2eb.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5BA0OxSlI-4PzPkAlLU-0_NIAEFgFPiM',
    appId: '1:834509746782:web:1f73d0d7ad5baad083facf',
    messagingSenderId: '834509746782',
    projectId: 'storytelling-audio-web-bc2eb',
    authDomain: 'storytelling-audio-web-bc2eb.firebaseapp.com',
    storageBucket: 'storytelling-audio-web-bc2eb.firebasestorage.app',
    measurementId: 'G-V46254GESR',
  );
}
