// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCygIMGeVHYer3wfVIUl5iHX-3Gpbcgfw',
    appId: '1:704251086923:web:0eb7ee3a19da4afdeb65ce',
    messagingSenderId: '704251086923',
    projectId: 'storytelling-audio-app',
    authDomain: 'storytelling-audio-app.firebaseapp.com',
    storageBucket: 'storytelling-audio-app.firebasestorage.app',
    measurementId: 'G-SVC1BRTRS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4DTgWdKla7i_T6u1frvOTOCukCcrP0IE',
    appId: '1:704251086923:android:d7eb9c2ba3f6f741eb65ce',
    messagingSenderId: '704251086923',
    projectId: 'storytelling-audio-app',
    storageBucket: 'storytelling-audio-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6z4W0pfSv4G1dE8eezh86s9jrC7SxmxQ',
    appId: '1:704251086923:ios:4fc76e65dbe0237beb65ce',
    messagingSenderId: '704251086923',
    projectId: 'storytelling-audio-app',
    storageBucket: 'storytelling-audio-app.firebasestorage.app',
    iosBundleId: 'com.example.storytellingAudioApp',
  );

}